# Data Configuration
data_dir: "/Users/Ronit/Downloads/aptos2019-blindness-detection"
img_size: 224

# Model Configuration
pretrained: True
num_classes: 1

# Training Configuration
batch_size: 32
epochs: 30
lr: 0.0001
weight_decay: 1e-4

# Logging
wandb_project: "diabetic_retinopathy"
run_name: "aptos_binary_classification"
save_dir: "checkpoints"

# Data Augmentation
augmentation: True
